GET http://localhost:8000/players/


###
POST http://localhost:8000/players/add-player
Content-Type: application/json

{
    "username": "Peter",
    "score": 25
}


###
GET http://localhost:8000/players/Peter
// Virker

###
GET http://localhost:8000/players/Lars
// Fejl, as expected